minimumReleaseAgeExclude:
  - '@expo/cli@57.0.7'
  - '@expo/config-plugins@57.0.4'
  - '@expo/config@57.0.4'
  - '@expo/fingerprint@0.20.4'
  - '@expo/image-utils@0.11.2'
  - '@expo/local-build-cache-provider@57.0.3'
  - '@expo/metro-config@57.0.4'
  - '@expo/prebuild-config@57.0.6'
  - '@expo/require-utils@57.0.2'
  - expo-asset@57.0.4
  - expo-constants@57.0.4
  - expo-modules-autolinking@57.0.6
  - expo-modules-core@57.0.4
  - expo-modules-jsi@57.0.2
  - expo@57.0.5
